### PR TITLE
(doc) Minor modifications

### PR DESCRIPTION
**Pull request by gep13**

### CODE REVIEW

**Comment by gep13** [comment]
@chwilfing just wanted to check if you had seen this or not, thanks.

**Comment by gep13** [comment]
@chwilfing just wanted to check...

Was there something wrong with this PR?  Are you going to do the work manually?

Thanks

**Comment by chwilfing** [comment]
Really sorry, just very new to github... thanks for your request.

**Comment by gep13** [comment]
>@chwilfing said...
Really sorry, just very new to github... thanks for your request.

No need to apologise, I was just curious about if something else was required.

Thanks for merging!

**Pull request merged**
